# Generated by Django 2.1.4 on 2020-04-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
                ('click', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('A1', models.CharField(max_length=255)),
                ('A2', models.CharField(max_length=255)),
                ('A3', models.CharField(max_length=255)),
                ('A4', models.CharField(max_length=255)),
                ('A5', models.CharField(max_length=255)),
                ('A6', models.CharField(max_length=255)),
                ('A7', models.CharField(max_length=255)),
                ('A8', models.CharField(max_length=255)),
                ('A9', models.CharField(max_length=255)),
                ('A10', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('theta', models.CharField(max_length=255)),
            ],
        ),
    ]
