# Generated by Django 2.1.4 on 2020-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
