# Generated by Django 2.1.4 on 2020-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0002_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
