# Generated by Django 2.1.4 on 2020-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
