# Generated by Django 2.1.4 on 2020-04-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0004_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genres_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Genres')),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Movie')),
            ],
        ),
    ]
