# Generated by Django 2.1.4 on 2020-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0005_genres_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='name_ch',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
