# Generated by Django 2.1.4 on 2020-04-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0007_auto_20200407_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_genres',
            old_name='Genres_id',
            new_name='Genres',
        ),
        migrations.RenameField(
            model_name='movie_genres',
            old_name='Movie_id',
            new_name='Movie',
        ),
    ]
