# Generated by Django 2.1.4 on 2020-04-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0008_auto_20200407_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('A1', models.CharField(max_length=255)),
                ('A2', models.CharField(max_length=255)),
                ('A3', models.CharField(max_length=255)),
                ('A4', models.CharField(max_length=255)),
                ('A5', models.CharField(max_length=255)),
                ('A6', models.CharField(max_length=255)),
                ('A7', models.CharField(max_length=255)),
                ('A8', models.CharField(max_length=255)),
                ('A9', models.CharField(max_length=255)),
                ('A10', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('theta', models.CharField(max_length=255)),
            ],
        ),
    ]
