# Generated by Django 2.1.4 on 2020-04-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0009_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cluster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Cluster'),
            preserve_default=False,
        ),
    ]
