# Generated by Django 2.1.4 on 2020-04-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0010_user_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Cluster'),
        ),
        migrations.AddField(
            model_name='collect',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.User'),
        ),
    ]
