# Generated by Django 2.1.4 on 2020-04-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0012_auto_20200409_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Cluster'),
        ),
        migrations.AddField(
            model_name='record',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.User'),
        ),
    ]
