# Generated by Django 2.1.4 on 2020-04-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0013_auto_20200413_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Permission')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Role')),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Role')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Cluster'),
        ),
        migrations.AddField(
            model_name='user_role',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.User'),
        ),
    ]
