# Generated by Django 2.1.4 on 2020-04-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0014_auto_20200414_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='url',
            new_name='describe',
        ),
        migrations.AlterField(
            model_name='user',
            name='Cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Cluster'),
        ),
    ]
