# Generated by Django 2.1.4 on 2020-04-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0015_auto_20200414_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='click',
            new_name='number_people',
        ),
        migrations.AlterField(
            model_name='user',
            name='Cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Cluster'),
        ),
    ]
