# Generated by Django 2.1.4 on 2020-04-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsystem', '0016_auto_20200415_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='Cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsystem.Cluster'),
        ),
    ]
